all: sortieralgorithmen clean

sortieralgorithmen:
	clang++ sortieralgorithmen.cpp -o Sortieralgorithmen
	chmod +x Sortieralgorithmen
	./Sortieralgorithmen

clean:
	$(RM) *.o
	$(RM) *.out
	$(RM) Sortieralgorithmen