all: 2a 2b 2c clean

2a:
	clang++ a_insertionsort.cpp -o Aufgabe2a
	chmod +x Aufgabe2a
	./Aufgabe2a

2b:
	clang++ b_bubblesort.cpp -o Aufgabe2b
	chmod +x Aufgabe2b
	./Aufgabe2b

2c:
	clang++ c_selectionsort.cpp -o Aufgabe2c
	chmod +x Aufgabe2c
	./Aufgabe2c

2d:
	clang++ d_quicksort.cpp -o Aufgabe2d
	chmod +x Aufgabe2d
	./Aufgabe2d

clean:
	$(RM) *.o
	$(RM) *.out
	$(RM) Aufgabe2*